apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-bridge-mapping-physnet-vmdata
spec:
  nodeSelector:
    kubernetes.io/hostname: workerbee1
  desiredState:
    ovn:
      bridge-mappings:
      - localnet: physnet-vmdata
        bridge: br-ex 
        state: present
