apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-tls-cert
  namespace: openshift-console
spec:
  isCA: false
  secretName: app-tls-cert-secret
  issuerRef:
    name: letsencrypt-digitalocean
    kind: ClusterIssuer
  dnsNames:
  - keam.org
  - '*.keam.org'

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: app-tls
  namespace: openshift-console
  labels:
    app: console
spec:
  host: console.keam.org
  to:
    kind: Service
    name: console
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
    externalCertificate:
      name: app-tls-cert-secret

