apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-helm-chart-repo-clusterrole
rules:
- apiGroups: ["helm.openshift.io"]
  resources: ["helmchartrepositories"]
  verbs: ["*"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-helm-chart-repo-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: all-helm-chart-repo-clusterrole
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
