apiVersion: v1
kind: PersistentVolume
metadata:
  name: fedora-pv
  namespace: jkeam
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /dev/nvme0n1
  resources:
    requests:
      storage: 40Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master1
