apiVersion: v1
kind: PersistentVolume
metadata:
  name: fedora-os-images
  namespace: openshift-virtualization-os-images
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /dev/nvme0n1
  resources:
    requests:
      storage: 32Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master1
  claimRef:
    name: fedora-1217dcc8c58d
    namespace: openshift-virtualization-os-images
