apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresdb-tekton-results-postgres
  namespace: openshift-pipelines
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /dev/nvme0n1
  resources:
    requests:
      storage: 1Gi
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master1
  claimRef:
    name: postgredb-tekton-results-postgres-0
    namespace: openshift-pipelines
