apiVersion: v1
kind: Secret
metadata:
  name: cloudinitsecret
type: Opaque
stringData:
  userData: |
    #cloud-config
    user: fedora
    password: axqa-jtsr-isq2
    chpasswd: { expire: False }
    package_update: true
    package_upgrade: true
    timezone: 'America/New_York'
    hostname: fedora
    packages:
    - x11vnc
    - net-tools
    - firefox
    - neovim
    - git
    - tmux
    - zsh
    - wget
    - xrdp
    - xorgxrdp
    - fastfetch
    write_files:
    - content: |
        /usr/bin/xfce4-session
      path: /home/fedora/.xinitrc
      permissions: '0744'
      owner: 'fedora:fedora'
      defer: true
    - content: |
        allowed_users = anybody
      path: /etc/X11/Xwrapper.config
      permissions: '0744'
      owner: 'root:root'
      defer: false
    - content: |
        #!/bin/bash
        nohup startx > ./startx-nohup.log 2>&1 &
      path: /home/fedora/startx.sh
      permissions: '0744'
      owner: 'fedora:fedora'
      defer: true
    - content: |
        #!/bin/bash
        sudo systemctl start firewalld
        sudo firewall-cmd --add-service vnc-server
        # `sudo x11vnc -storepasswd` the first time to create a password
        # also helps to boot the vncserver first to test the connection
        nohup sudo x11vnc -display :0 -N -nevershared -forever -noxdamage -usepw -no6 -noipv6 -nowireframe -norepeat -ncache 0 > startvnc-nohup.log 2>&1 &
      path: /home/fedora/startvnc.sh
      permissions: '0744'
      owner: 'fedora:fedora'
      defer: true
    - content: |
        #!/bin/bash
        sudo systemctl start firewalld
        sudo firewall-cmd --add-service=rdp --permanent
        sudo firewall-cmd --reload
        sudo systemctl enable --now xrdp
        echo "xfce4-session" > ~/.xsession
        chmod +x ~/.xsession
      path: /home/fedora/startrdp.sh
      permissions: '0744'
      owner: 'fedora:fedora'
      defer: true
    - content: |
        #!/bin/bash
        export OPENSHIFT_TOKEN='sha256~stuff'
        oc login --token=$OPENSHIFT_TOKEN --server=https://apiserver.openshift-kube-apiserver.svc.cluster.local
      path: /home/fedora/oc-login.sh
      permissions: '0744'
      owner: 'fedora:fedora'
      defer: true
    runcmd:
    - dnf group install xfce-desktop -y
    - nmcli connection modify "Wired connection 1" ipv4.addresses 192.168.1.253/24
    - nmcli connection modify "Wired connection 1" ipv4.dns 192.168.1.201
    - nmcli connection modify "Wired connection 1" ipv4.method manual
    - nmcli connection down "Wired connection 1"
    - nmcli connection up "Wired connection 1"
    - firewall-cmd --add-service=vnc-server --permanent
    - firewall-cmd --reload
    - curl -fLo /home/fedora/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    - curl -fLo /home/fedora/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    - mkdir -p /home/fedora/dev/projects/dotfiles
    - git clone https://github.com/jkeam/dotfiles /home/fedora/dev/projects/dotfiles
    - cp /home/fedora/dev/projects/dotfiles/.vimrc /home/fedora
    - mkdir -p /home/fedora/.config/nvim
    - cp /home/fedora/dev/projects/dotfiles/.vimrc /home/fedora/.config/nvim/init.vim
    - curl -fsSL -o /home/fedora/install-ohmyzshell.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    - chown fedora:fedora -R /home/fedora
    - chmod 777 /home/fedora/install-ohmyzshell.sh
    - su -c "/home/fedora/install-ohmyzshell.sh" fedora
    - rm /home/fedora/install-ohmyzshell.sh
    - curl -fsSL -o /home/fedora/Hack.zip https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/Hack.zip
    - mkdir -p /home/fedora/.local/share/fonts
    - unzip -d /home/fedora/.local/share/fonts Hack.zip
    - fc-cache -fv
    - rm Hack.zip
    - su -c "echo 'DONE'" fedora
