kind: Service
apiVersion: v1
metadata:
  name: fedora
  namespace: vms
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 22000
      targetPort: 22
      nodePort: 30000
      name: ssh
    - protocol: TCP
      port: 59000
      targetPort: 5900
      nodePort: 30001
      name: vnc
  internalTrafficPolicy: Cluster
  type: NodePort
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    kubevirt.io/domain: fedora
