apiVersion: v1
kind: Service
metadata:
  name: fedora
  namespace: vm
  labels:
    app: fedora
spec:
  ports:
  - name: ssh
    nodePort: 30000
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: fedora
  type: NodePort
