apiVersion: v1
kind: Secret
metadata:
  name: jobs-ssh-key
  namespace: vms
data:
  key: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCZ1FDTHNVREZYU0oxQisxUHVsamE4cjA3TzlldGVVNzA1enRiNXVwSnFKM25BL2xkNUtZTmhSY1EwdmQ4NkNXbG85TlVNNTlrMU03ejd6VWtrUm93TU5SSkZOSHNaVFB3NHZvdjNBeXBydWduZGFsemtCcCtIR3RHVDVYRnFBZmJTYjROMEFWREdWSnZoajB0QjJPOU9OU0JwU2VhcXJDTXFBeVk2U3pkUitURHVXUk1YQWVjUVlWY3pzM0tSV2l1bTNzSisrUzIxWU9TNUNTR1E1R0JvbnRuSmdtT0dONkYwbkp3NDNLR2QwclV4Q1NZUWtBczJnTDBreEE0YjRFVkc1M08wMDBaSE4xaFBzK0NMdjJBakw2bDQrT3U1aTBzaHZKeTROR0x1MUdiTDdMZFlSUytYeVd1QVRaYm94Y2IvVnpVd2o0dWlTZEgwOFNqYVRrL1FtNVBUenZXTWlENUhJMThmMFRVSlJEenE5U0Yrd3FlTi9pYUN5TFo2dXJmSERuQ2NyUXdpTzZpOWI0RTBSYVRmYTl4RmNsYXBtaWhPY0pJVlAvbkExR01vdzBlOGtZTjhYT3BhazErbXJuajhvelQ5QjZkellTUVA3ZE1BTHdPMjVSdVVHSDRtdU9wTXIxK3Bmc0xweGlMWFNRMWtSUEZVbkNRWEJLQ3VvbmhOZVU9IGprZWFtQGpvYnM=
type: Opaque
