apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    vm.kubevirt.io/validations: |
      [
        {
          "name": "minimal-required-memory",
          "path": "jsonpath::.spec.domain.memory.guest",
          "rule": "integer",
          "message": "This VM requires more memory.",
          "min": 2147483648
        }
      ]
  labels:
    app: fedora
    kubevirt.io/dynamic-credentials-support: 'true'
    vm.kubevirt.io/template: fedora-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.29.1
  name: fedora
  namespace: vms
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: fedora
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 40Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: fedora
        kubevirt.io/size: small
    spec:
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {}
            source:
              secret:
                secretName: ada-ssh-key
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - macAddress: '02:01:b9:00:00:04'
              masquerade: {}
              model: virtio
              name: default
            - macAddress: '02:01:b9:00:00:0c'
              bridge: {}
              model: virtio
              name: bridge
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            bios: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
        - name: default
          pod: {}
        - name: bridge
          multus:
            networkName: br-ex-network
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: fedora
          name: rootdisk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: axqa-jtsr-isq2
              chpasswd: { expire: False }
              package_update: true
              package_upgrade: true
              timezone: 'America/New_York'
              hostname: fedora
              packages:
              - x11vnc
              - net-tools
              - chromium
              - neovim
              - git
              - tmux
              write_files:
              - content: |
                  /usr/bin/xfce4-session
                path: /home/fedora/.xinitrc
                permissions: '0744'
                owner: 'fedora:fedora'
                defer: true
              - content: |
                  allowed_users = anybody
                path: /etc/X11/Xwrapper.config
                permissions: '0744'
                owner: 'root:root'
                defer: false
              - content: |
                  #!/bin/bash
                  nohup startx > ./startx-nohup.log 2>&1 &
                path: /home/fedora/startwm.sh
                permissions: '0744'
                owner: 'fedora:fedora'
                defer: true
              runcmd:
              - dnf group install xfce-desktop -y
              - nmcli connection modify "Wired connection 1" ipv4.addresses 192.168.1.203/24
              - nmcli connection modify "Wired connection 1" ipv4.gateway 192.168.1.1
              - nmcli connection modify "Wired connection 1" ipv4.dns 192.168.1.201
              - nmcli connection modify "Wired connection 1" ipv4.method manual
              - nmcli connection down "Wired connection 1"
              - nmcli connection up "Wired connection 1"
              - firewall-cmd --add-service=vnc-server --permanent
              - firewall-cmd --reload
              - curl -fLo /home/fedora/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
              - curl -fLo /home/fedora/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
              - mkdir -p /home/fedora/dev/projects/dotfiles
              - git clone https://github.com/jkeam/dotfiles /home/fedora/dev/projects/dotfiles
              - cp /home/fedora/dev/projects/dotfiles/.vimrc /home/fedora
              - mkdir -p /home/fedora/.config/nvim
              - cp /home/fedora/dev/projects/dotfiles/.vimrc /home/fedora/.config/nvim
              - curl -fsSL -o /home/fedora/install-ohmyzshell.sh https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
              - chown fedora:fedora -R /home/fedora
              - su -c "/home/fedora/install-ohmyzshell.sh" fedora
          name: cloudinitdisk
