apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: fedora
    kubevirt.io/dynamic-credentials-support: 'true'
    vm.kubevirt.io/template: fedora-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.34.1
  name: fedora
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: fedora
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 40Gi
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: fedora
        kubevirt.io/size: small
    spec:
      accessCredentials:
        - sshPublicKey:
            propagationMethod:
              noCloud: {}
            source:
              secret:
                secretName: jobs-ssh-key
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - macAddress: '02:01:b9:00:00:04'
              masquerade: {}
              model: virtio
              name: default
            - macAddress: '02:01:b9:00:00:0c'
              bridge: {}
              model: virtio
              name: bridge
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            bios: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 4Gi
        resources: {}
      networks:
        - name: default
          pod: {}
        - name: bridge
          multus:
            networkName: physnet-vmdata
      nodeSelector:
        kubernetes.io/hostname: workerbee1
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          dataVolume:
            name: fedora
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: cloudinitsecret
