kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: httpd-data-pvc
  namespace: cluster-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  volumeMode: Filesystem
